name: Tom Wire's Blog
description: Blogging about stuffs
meta_description: "Tom Wire Blog. Blogging about ASP.NET, Ruby on Rails and anything in between"

# markdown: redcarpet
# pygments: true
highlighter: rouge
logo: false
paginate: 15

# Details for the RSS feed generator
url:            'http://thesilverbadger.co.uk'
author:         'Tom Wire'
